const categoryTitles = {
  info: "Информация",
  body: "Корпус",
  howitzer: "Гаубица",
  mlrs: "РСЗО",
  mortar: "Миномёт",
  main_gun: "Орудие",
  atgm: "ПТУР",
  autocannon: "Автопушка",
  autocannon2: "Автопушка 2",
  grenade_launcher: "Гранатомёт",
  mmg: "Пулемёт",
  mmg2: "Пулемёт 2",
  mmg3: "Пулемёт 3",
  flamethrower: "Огнемёт",
  sam: "ЗУР",
  assault_rifle: "Штурмовая винтовка",
  lmg: "Ручной пулемёт",
  flamethrower_hand: "Ручной огнемёт",
  rocket_launcher: "Ракетная ПУ",
  sniper_rifle: "Снайперская винтовка",
  law: "РПГ",
  rocket_pod: "НУР",
  rocket_pod2: "НУР 2",
  anti_radar: "ПРР",
  agm: "Воздух-земля",
  bomb: "Бомбы",
  cluster_bomb: "Кассетные бомбы",
  napalm_bomb: "Напалмовые бомбы",
  lgb: "Бомба с лазерным наведением",
  aam: "Воздух-воздух",
  aam2: "Воздух-воздух 2",
};

export default categoryTitles;
