const propertyLabels = {
  // info
  class: "Класс",
  country: "Страна",
  cost: "Стоимость",
  year: "Год",
  prototype: "Прототип",
  // body
  hp: "Сила",
  training: "Подготовка",
  armor_front: "Броня (лоб)",
  armor_side: "Броня (борт)",
  armor_rear: "Броня (корма)",
  armor_top: "Броня (верх)",
  size: "Размер",
  ecm: "РЭП, %",
  stealth: "Незаметность",
  optics: "Оптика",
  air_detection: "Обн. возд. целей",
  speed: "Скорость, км/ч",
  speed_road: "Дор. скорость, км/ч",
  amphibious: "Амфибия, км/ч",
  turn_radius: "Радиус поворота",
  fuel: "Топливо, л",
  supply: "Припасы, л",
  autonomy: "Автономность, км",
  tot: "ВДЦ, с",
  // weapons
  name: "Название",
  ammo: "Кол-во снарядов",
  attr_kin: "[КИН]",
  attr_ptk: "[ПТК]",
  attr_stc: "[СТЦ]",
  attr_fg: "[ФГ]",
  attr_upr: "[УПР]",
  attr_pa: "[ПА]",
  attr_smn: "[СМН]",
  attr_ppvo: "[ППВО]",
  attr_rls: "[РЛС]",
  attr_kass: "[КАСС]",
  attr_nplm: "[НПЛМ]",
  attr_korr: "[КОРР]",
  attr_dym: "[ДЫМ]",
  attr_bb: "[ББ]",
  range_ground: "Дальность: наземные, м",
  range_helicopters: "Дальность: вертолёты, м",
  range_airplanes: "Дальность: самолёты, м",
  accuracy: "Точность, %",
  dispersion: "Рассеивание, м",
  stabilizer: "Стабилизатор, %",
  ap_power: "Бронебойность",
  he_power: "Фугас",
  suppression: "Подавление",
  rate_of_fire: "Скорострельность, в мин",
};

export default propertyLabels;
